name: Python Script Automation
on:
    schedule:
        - cron: "30 0 * * *"
jobs:
    run_script:
        runs-on: ubuntu-latest
        steps:
            - name: Call Streamlit Crawler
              run: curl -X GET "https://g-drive-api-test.streamlit.app/streamlit_test.py"

#    schedule:
#       - cron: "* * * * *"
#                ^ ^ ^ ^ ^
#                | | | | |
#           minuto | | | |
#                ora | | |
#      giorno del mese | |
#                    ese |
#   giorno della settimana